"""Deterministic adaptation of libdither 7bf49c5 (see THIRD_PARTY_NOTICES.md).

Treat camera Y as neutral sRGB. Magic matches default grayscale import exactly;
1D uses Q24 instead of upstream doubles. Neither uses random noise/jitter.
Run this to regenerate the portable core's table header.
"""
from pathlib import Path

MATRIX=(4,2,7,5,3,1,8,6,7,5,4,2,8,6,3,1)

def linear(v):
    c=v/255
    d=c/12.92 if c<=0.04045 else ((c+0.055)/1.055)**2.4
    return d*0.299+d*0.586+d*0.114

THRESHOLDS=bytes(next(v for v in range(256) if linear(v)+rank*(1/9)-0.5>0.5) for rank in MATRIX)
LINEAR_Q24=tuple(round(linear(v)*(1<<24)) for v in range(256))

if __name__=='__main__':
    target=Path(__file__).resolve().parents[1]/'firmware/ditherista_tables.h'
    text='/* Generated by tools/ditherista_tables.py; see THIRD_PARTY_NOTICES.md. */\n'
    text+='static const uint8_t pg_magic445[16]={'+','.join(map(str,THRESHOLDS))+'};\n'
    text+='static const int32_t pg_linear_q24[256]={\n'
    text+='\n'.join('    '+','.join(map(str,LINEAR_Q24[i:i+8]))+',' for i in range(0,256,8))+'\n};\n'
    target.write_text(text)
